use_frameworks!

platform :ios, '9.0'

target 'BhoomiUtilityFramework_Example' do
  pod 'BhoomiUtilityFramework', :path => '../'

  target 'BhoomiUtilityFramework_Tests' do
    inherit! :search_paths

    
  end
end
